<a href="https://colab.research.google.com/github/Bonface-3020/ACP-M13/blob/main/Basic_SQL_statements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3
database='database.sqlite'
conn=sqlite3.connect(database)
print("opened data successfuly")

opened data successfuly

In [4]:
import pandas as pd
tables=pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [5]:
team=pd.read_sql("""SELECT * FROM Team;""",conn)
team

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

In [6]:
MI_wins=pd.read_sql("""SELECT * FROM Match WHERE Match_Winner==7;""",conn)
MI_wins

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,336002,1,7,2008-04-29 00:00:00,1,5,1,2,2,7,1,7,44
1,336009,7,6,2008-05-04 00:00:00,1,9,6,1,1,29,1,7,49
2,336013,7,5,2008-05-07 00:00:00,1,9,7,1,2,7,1,7,73
3,336017,2,7,2008-05-28 00:00:00,1,1,7,1,2,9,1,7,149
4,336023,7,3,2008-05-14 00:00:00,1,4,7,1,2,9,1,7,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,980946,4,7,2016-04-25 00:00:00,9,33,4,1,1,25,1,7,17
76,980952,7,1,2016-04-28 00:00:00,9,4,7,1,2,6,1,7,57
77,980962,12,7,2016-05-01 00:00:00,9,32,7,1,2,8,1,7,57
78,980986,2,7,2016-05-11 00:00:00,9,1,7,1,2,6,1,7,413
79,980998,7,6,2016-05-15 00:00:00,9,25,6,1,1,80,1,7,413

In [7]:
Match=pd.read_sql("""SELECT * FROM Match;""",conn)
Match

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,981016,6,2,2016-05-22 00:00:00,9,27,2,1,2,6.0,1,2.0,8.0
573,981018,13,2,2016-05-24 00:00:00,9,1,2,1,2,4.0,1,2.0,110.0
574,981020,11,1,2016-05-25 00:00:00,9,3,1,1,1,22.0,1,11.0,163.0
575,981022,13,11,2016-05-27 00:00:00,9,3,11,1,2,4.0,1,11.0,187.0
576,981024,2,11,2016-05-29 00:00:00,9,1,11,2,1,8.0,1,11.0,385.0

In [8]:
min_max_margin=pd.read_sql("""SELECT MIN(Win_Margin),MAX(Win_Margin) FROM Match;""",conn)
min_max_margin

   MIN(Win_Margin)  MAX(Win_Margin)
0                1              144